# Generated by Django 3.0.7 on 2020-10-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggroup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
